sensor:
  - platform: Heweather
    city: beijing
    aqi_city: beijing
    appkey: f125e4670f1459bb87657ace3debdf3
    options:
      - fl
      - tmp
      - cond_txt
      - wind_spd
      - hum
      - pcpn
      - press
      - vis
      - wind_sc
      - aqi
      - main
      - qlty
      - pm10
      - pm25
      - comf
      - cw
      - drsg
      - flu
      - sport
      - trav
      - uv
      - wind_dir
      - tmp_max
      - tmp_min
      - pop

group:
  heweather:
    name: 天气情况
    view: yes
    icon: mdi:weather-partlycloudy
    entities:
      - group.weather_index 
      - group.air_index
      - group.lives_index
  weather_index:   
    name: 天气
    view: no 
    entities:
      - sensor.heweather_fl
      - sensor.heweather_tmp      
      - sensor.heweather_cond_txt
      - sensor.heweather_wind_spd
      - sensor.heweather_hum
      - sensor.heweather_pcpn
      - sensor.heweather_tmp_max
      - sensor.heweather_tmp_min 
      - sensor.heweather_pop      
  air_index:  
    name: 空气
    view: no 
    entities:      
      - sensor.heweather_pres
      - sensor.heweather_vis
      - sensor.heweather_wind_sc
      - sensor.heweather_aqi
      - sensor.heweather_main
      - sensor.heweather_qlty
      - sensor.heweather_pm10 
      - sensor.heweather_pm25
      - sensor.heweather_wind_dir
  lives_index:  
    name: 指数
    view: no 
    entities:     
      - sensor.heweather_comf
      - sensor.heweather_cw
      - sensor.heweather_drsg
      - sensor.heweather_flu
      - sensor.heweather_sport
      - sensor.heweather_trav
      - sensor.heweather_uv

automation:  
  - alias: weather_report
    initial_state: true
    trigger:
      - platform: time
        hours: 7
        minutes: 30
        seconds: 0
     
    condition:
      condition: numeric_state
      entity_id: sensor.weather_temperature
      #判断气温是否高于34°C
      above: 1  
        
    action:
      - service: tts.baidu_say             ###############你自己的TTS
        data_template:
          entity_id: media_player.mpd       ###############你自己的播放器
          message: "现在播报天气信息。今日最高温度，{{states('sensor.heweather_tmp_max')}}°C, 今日最低温度{{states('sensor.heweather_tmp_min')}}°C，实时体感温度{{states('sensor.heweather_fl')}}°C, 实时室外温度{{states('sensor.heweather_tmp')}}°C, 空气质量{{states('sensor.heweather_qlty')}}"